# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FP5u_dBDRgYpiOAzjlBoMQBnTckRPuVj
"""

import gzip
import simplejson
import pandas as pd
import matplotlib.pyplot as plt

def parse(filename):
  f = gzip.open(filename, 'rt')
  entry = {}
  for l in f:
    l = l.strip()
    colonPos = l.find(':')
    if colonPos == -1:
      yield entry
      entry = {}
      continue
    eName = l[:colonPos]
    rest = l[colonPos+2:]
    entry[eName] = rest
  yield entry

# Collect data into a list of dictionaries
data = []
for e in parse("Watches.txt.gz"):
  data.append(e)

# Create DataFrame
df = pd.DataFrame(data)

# Convert 'review/score' to numeric, handling potential errors
df['review/score'] = pd.to_numeric(df['review/score'], errors='coerce')

# Filter out NaN values that might result from 'coerce' during conversion
df_filtered = df.dropna(subset=['review/score'])

# Count the occurrences of each review score
score_counts = df_filtered['review/score'].value_counts().sort_index()

# Create the bar graph
plt.figure(figsize=(8, 5))
score_counts.plot(kind='bar', color='skyblue')
plt.title('Distribution of Product Review Scores')
plt.xlabel('Review Score')
plt.ylabel('Number of Reviews')
plt.xticks(rotation=0) # Ensure x-axis labels are readable
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout() # Adjust layout to prevent labels from being cut off
plt.show()

# Group by product/productId and count the number of reviews for each product
review_counts = df['product/productId'].value_counts()

#getting the top 5 most reviewed products
top_5_products = review_counts.head(5)

print("Top 5 Most Reviewed Products:")
display(top_5_products)

# Calculate the average review score for each product
average_scores = df.groupby('product/productId')['review/score'].mean().sort_values(ascending=False)

print("Average Review Score per Product (Top 10):")
display(average_scores.head(10))

product_id = 'B000NLZ4A2'
product_df = df[df['product/productId'] == product_id].copy()

# Convert 'review/time' to datetime objects
product_df['review/time'] = pd.to_datetime(product_df['review/time'], unit='s')

# Sort by time to ensure a proper time series plot
product_df = product_df.sort_values(by='review/time')

plt.figure(figsize=(12, 6))
plt.plot(product_df['review/time'], product_df['review/score'], marker='o', linestyle='-')
plt.title(f'Review Scores Over Time for Product ID: {product_id}')
plt.xlabel('Review Date')
plt.ylabel('Review Score')
plt.grid(True)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# Create the bar graph using the previously calculated score_counts
plt.figure(figsize=(10, 6))
score_counts.plot(kind='bar', color='lightcoral')
plt.title('Overall Distribution of Review Scores Across All Products')
plt.xlabel('Review Score')
plt.ylabel('Number of Reviews')
plt.xticks(rotation=0)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

import pandas as pd

data = []
for e in parse("Watches.txt.gz"):
  data.append(e)

df = pd.DataFrame(data)
display(df.head())

df['product/productId'].unique()

